fix(kwallet): empty wallet key query
When querying a key in an empty kwallet wallet, we receive the following error:
```
Error: unexpected end of JSON input
```
This is because the `k.wallet.ReadEntry` returns empty bytes and no error. Hence we should handle a case for empty bytes.

Reference: https://github.com/cosmos/cosmos-sdk/issues/9562