Fix error:
../../../../1.12.5/src/github.com/99designs/keyring/pass.go:34:3: cannot
use pass (type *passKeyring) as type Keyring in return argument:
        *passKeyring does not implement Keyring (missing GetMetadata method)